[versions]
activityCompose = "1.10.1"
agp = "8.12.3"
animationAndroid = "1.8.3"
appcompat = "1.7.1"
coreKtx = "1.16.0"
datastore = "1.1.7"
escposThermalprinterAndroid = "3.3.0"
espressoCore = "3.7.0"
exifinterface = "1.4.1"
foundationAndroid = "1.8.3"
html2bitmap = "1.10"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.0"
kotlinterGradlePlugin = "5.2.0"
material = "1.12.0"
material3Android = "1.3.2"
protobufGradlePlugin = "0.9.5"
protobufKotlinLite = "4.31.1"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-animation-android = { group = "androidx.compose.animation", name = "animation-android", version.ref = "animationAndroid" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }
androidx-foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "foundationAndroid" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
escpos-thermalprinter-android = { group = "com.github.DantSu", name = "ESCPOS-ThermalPrinter-Android", version.ref = "escposThermalprinterAndroid" }
html2bitmap = { group = "com.izettle", name = "html2bitmap", version.ref = "html2bitmap" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
protobuf-gradle-plugin = { group = "com.google.protobuf", name = "protobuf-gradle-plugin", version.ref = "protobufGradlePlugin" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobufKotlinLite" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinter-plugin = { id = "org.jmailen.kotlinter", version.ref = "kotlinterGradlePlugin" }
protobuf-gradle-plugin = { id = "com.google.protobuf", version.ref = "protobufGradlePlugin" }